import { WebGLRenderer } from 'three';
import { GLBType } from 'common/src/glb-iframe/types';
export declare let renderer: WebGLRenderer;
export declare const init: (glbPath: string, glbType: GLBType, baseUri: string, characterMeta?: {
    Type: "Boss";
    BossType: "VinnieVintage" | "LumberJack" | "Banksy" | "SirBigEyeLot" | "CapnTorrents" | "AguaViva" | "CanCan" | "DrPrepper" | "LadyDeVil" | "Cthulhu" | "MasaBot" | "Destructo" | "Illusionist" | "MetaRaider" | "Patch" | "Cleopawtra" | "Guillotina" | "TiredGuy" | "Peter51" | "Pound" | "Dali" | "RelicHunter" | "PickANick" | "Avocardano" | "KelBot" | "SpaceCowboy" | "CapnAquamarine" | "Rumi" | "UrbanOccultist" | "SwarmQueen" | "VenusIII" | "HotCakes" | "FakeGhost" | "Multiply" | "Warhol" | "Executioner" | "SorryDave" | "Blu65" | "NightShade" | "Additive" | "Picasso" | "Goxxer" | "BluesBrosElwood" | "BlueShirtGuy" | "Marvin" | "BluesBrosJake" | "BadBetty" | "Breadmancer" | "MetaPlayerOne" | "MetaCat" | "GothQueen" | "MetaFighter" | "GreenTracksuit" | "SkullKid" | "Burguy" | "MetaQueen" | "MetaOctopusGod" | "PlayerOne2384" | "PlayerTwo2384" | "HolographicPlayerOne2384" | "HolographicPlayerTwo2384" | "HoneyRhingers" | "JiangshiGhost" | "PeterInDaHood" | "WitchBot" | "ConeHead" | "MsTofelees" | "RobotQueenHolo" | "Antoinette" | "Crustae-Sean" | "NinjaFrogBlack" | "NinjaFrogBlue" | "NinjaFrogOrange" | "NinjaFrogPink";
    Accessory: "IvySprite" | "LoveWings" | "FrankieFish" | "MetaverseDaily" | "Juicy" | "JadeOrb" | "AquaBomb" | "Nano" | "GameBoy" | "Bubbles" | "Trophy" | "Beau" | "ElderLeaf" | "Wildfire" | "Metalite" | "Chilli" | "Hector" | "Pennant" | "HotPack" | "ProtoFluf" | "Protector" | "Flan" | "Jerry" | "Wyse" | "BadBatch" | "Illuminator" | "Lasso" | "Shuriken" | "BigBow" | "InfoScroll" | "Macey" | "Livewire" | "Communicator" | "Bludgeon" | "FunHammer" | "Quencher" | "HotDog" | "Micro" | "FunGuy" | "ProtoThingie" | "Pixel" | "Ozmaton" | "Sundae" | "Croissant" | "Fries" | "Kebab" | "Goldie" | "MagicPlunger" | "Flickr" | "FlameSword" | "SnoCone" | "Pizza" | "Blinky" | "Chunk" | "Drumstick" | "Scrappy" | "CrossBow" | "TimeKeeper" | "Beemer" | "Blob" | "Cooper" | "Pocket" | "Slither" | "Casper" | "Radius" | "Sprout" | "Burger" | "Bomba" | "Healer" | "O2Tank" | "BoomStick" | "Soda" | "IceAxe" | "Grappler" | "Wayfinder" | "MiniVamp" | "Sparky" | "Sandwich" | "Squeek" | "Squawk" | "Peeker" | "Slowpoke" | "Donut" | "Wallet" | "Tink" | "PinkScroll" | "WoodHelm" | "SpiralBlaze" | "Sporious" | "HateFork" | "MrFLUF" | "ShortSword" | "ZenSphere" | "PureLove" | "AlterLeaf" | "Laika" | "Quackinator" | "LabRat" | "GameOn" | "MiniWhale" | "Opticon" | "AlteredSprite" | "CrawlR" | "CyloBowl" | "HiveSupply" | "HiTechBlob" | "NanoSphere" | "HotFix" | "RedReader" | "Daemo" | "TitanWings" | "PurgeBomb" | "BioBomb" | "ZalderLeaf" | "WingZ" | "DeadMouzy" | "BabyRabie" | "FrankenWhale" | "ToxicFlan" | "Zphere" | "TMND" | "GameOver" | "GhostChili" | "Eyesotope" | "DailyRag" | "BloodBath" | "Toxie" | "LilZ" | "ZORB" | "BrainBag" | "MutantSprite" | "Can" | "Baton" | "Scamper" | "GoldenIdol" | "FishBurger" | "DevilWings" | "OrangeSoda" | "PowerPack" | "Sqworm" | "ETHCrystal" | "Sceptre" | "Avo" | "BitBag" | "FakePumpkin" | "OrangeScroll" | "Syrup" | "BlueScroll" | "Salem" | "McFly" | "Console9k" | "PicnicStash" | "MasaFork" | "MetaNomicon" | "ButchersCleaver" | "Ssyrena" | "Mochi" | "Hatchet" | "HoneyHive" | "AirSpy" | "MiniUFO" | "Aquabomb" | "ShadeWings" | "WannaCry" | "EatCake" | "Candle" | "Schist" | "PocketWatch" | "BlackScroll" | "FlashGrenade" | "GunPod" | "Necronomicon" | "Hannay" | "GoldBowl" | "MagicMarble" | "ClassicSoccerBall" | "Ball" | "OR13" | "Beevis" | null;
} | {
    Type: "General";
    Family: "Original" | "ASMilated" | "Zombie" | "SuperHeroine";
    Hobby: "Roboticist" | "Summoner" | "Fighter" | "Trainer" | "Gourmet" | "Adventurer" | null;
    Body: "PlayerOne" | "PlayerTwo" | "BigEye" | "CrabGuy" | "OddFrog" | "GameBear" | "GreenIvy" | "CryptoNaut" | "LoveGhost" | "Snappy" | "Octopus" | "Quadrobot" | "MetaCaptain" | "BlobBeast" | "MissMeow" | "Occultist" | "ZenMaster" | "WinterQueen" | "HoneyPot" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "MeloPuff";
    Arms: "PlayerOne" | "PlayerTwo" | "BigEye" | "CrabGuy" | "OddFrog" | "GameBear" | "GreenIvy" | "CryptoNaut" | "LoveGhost" | "Snappy" | "Octopus" | "Quadrobot" | "MetaCaptain" | "BlobBeast" | "MissMeow" | "Occultist" | "ZenMaster" | "WinterQueen" | "HoneyPot" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "MeloPuff";
    Legs: "PlayerOne" | "PlayerTwo" | "BigEye" | "CrabGuy" | "OddFrog" | "GameBear" | "GreenIvy" | "CryptoNaut" | "LoveGhost" | "Snappy" | "Octopus" | "Quadrobot" | "MetaCaptain" | "BlobBeast" | "MissMeow" | "Occultist" | "ZenMaster" | "WinterQueen" | "HoneyPot" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "MeloPuff" | null;
    Topper: "PlayerOne" | "PlayerTwo" | "BigEye" | "CrabGuy" | "OddFrog" | "GameBear" | "GreenIvy" | "CryptoNaut" | "LoveGhost" | "Snappy" | "Octopus" | "Quadrobot" | "MetaCaptain" | "BlobBeast" | "MissMeow" | "Occultist" | "ZenMaster" | "WinterQueen" | "HoneyPot" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "MeloPuff" | "Quiff" | "Mane" | "Beret" | "Mohawk" | "BucketHat" | "FlowerHat" | "TopHat" | "BaseballCap" | "ArmyCap" | "CatEars" | "BearEars" | "Greaser" | "CowboyHat" | "PupEars" | "RabbitEars" | "DroopyEars" | "Antlers" | "BackwardsCap" | "PaperboyHat" | "VintageHat" | "FlatTop" | "Ponytail" | "Pigtail" | "Braids" | null;
    Eyes: "PlayerOne" | "PlayerTwo" | "BigEye" | "CrabGuy" | "OddFrog" | "GameBear" | "GreenIvy" | "CryptoNaut" | "LoveGhost" | "Snappy" | "Octopus" | "Quadrobot" | "MetaCaptain" | "BlobBeast" | "MissMeow" | "Occultist" | "ZenMaster" | "WinterQueen" | "HoneyPot" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "MeloPuff";
    Color: "Purple" | "Blue" | "DarkGreen" | "LightGreen" | "DarkOrange" | "LightOrange" | "Pink" | "White" | "Silver" | "Gold" | "ASMPurple" | "Fabulous" | "Holographic" | "Azure" | "Gray" | "Black" | "Gold " | null;
    AccentColor: "Purple" | "Blue" | "DarkGreen" | "LightGreen" | "DarkOrange" | "LightOrange" | "Pink" | "White" | "Silver" | "Gold" | "ASMPurple" | "Fabulous" | "Holographic" | "Azure" | "Gray" | "Black" | "Gold " | null;
    Accessory: "IvySprite" | "LoveWings" | "FrankieFish" | "MetaverseDaily" | "Juicy" | "JadeOrb" | "AquaBomb" | "Nano" | "GameBoy" | "Bubbles" | "Trophy" | "Beau" | "ElderLeaf" | "Wildfire" | "Metalite" | "Chilli" | "Hector" | "Pennant" | "HotPack" | "ProtoFluf" | "Protector" | "Flan" | "Jerry" | "Wyse" | "BadBatch" | "Illuminator" | "Lasso" | "Shuriken" | "BigBow" | "InfoScroll" | "Macey" | "Livewire" | "Communicator" | "Bludgeon" | "FunHammer" | "Quencher" | "HotDog" | "Micro" | "FunGuy" | "ProtoThingie" | "Pixel" | "Ozmaton" | "Sundae" | "Croissant" | "Fries" | "Kebab" | "Goldie" | "MagicPlunger" | "Flickr" | "FlameSword" | "SnoCone" | "Pizza" | "Blinky" | "Chunk" | "Drumstick" | "Scrappy" | "CrossBow" | "TimeKeeper" | "Beemer" | "Blob" | "Cooper" | "Pocket" | "Slither" | "Casper" | "Radius" | "Sprout" | "Burger" | "Bomba" | "Healer" | "O2Tank" | "BoomStick" | "Soda" | "IceAxe" | "Grappler" | "Wayfinder" | "MiniVamp" | "Sparky" | "Sandwich" | "Squeek" | "Squawk" | "Peeker" | "Slowpoke" | "Donut" | "Wallet" | "Tink" | "PinkScroll" | "WoodHelm" | "SpiralBlaze" | "Sporious" | "HateFork" | "MrFLUF" | "ShortSword" | "ZenSphere" | "PureLove" | "AlterLeaf" | "Laika" | "Quackinator" | "LabRat" | "GameOn" | "MiniWhale" | "Opticon" | "AlteredSprite" | "CrawlR" | "CyloBowl" | "HiveSupply" | "HiTechBlob" | "NanoSphere" | "HotFix" | "RedReader" | "Daemo" | "TitanWings" | "PurgeBomb" | "BioBomb" | "ZalderLeaf" | "WingZ" | "DeadMouzy" | "BabyRabie" | "FrankenWhale" | "ToxicFlan" | "Zphere" | "TMND" | "GameOver" | "GhostChili" | "Eyesotope" | "DailyRag" | "BloodBath" | "Toxie" | "LilZ" | "ZORB" | "BrainBag" | "MutantSprite" | "Can" | "Baton" | "Scamper" | "GoldenIdol" | "FishBurger" | "DevilWings" | "OrangeSoda" | "PowerPack" | "Sqworm" | "ETHCrystal" | "Sceptre" | "Avo" | "BitBag" | "FakePumpkin" | "OrangeScroll" | "Syrup" | "BlueScroll" | "Salem" | "McFly" | "Console9k" | "PicnicStash" | "MasaFork" | "MetaNomicon" | "ButchersCleaver" | "Ssyrena" | "Mochi" | "Hatchet" | "HoneyHive" | "AirSpy" | "MiniUFO" | "Aquabomb" | "ShadeWings" | "WannaCry" | "EatCake" | "Candle" | "Schist" | "PocketWatch" | "BlackScroll" | "FlashGrenade" | "GunPod" | "Necronomicon" | "Hannay" | "GoldBowl" | "MagicMarble" | "ClassicSoccerBall" | "Ball" | "OR13" | "Beevis" | null;
} | undefined) => Promise<void>;
