import { WebGLRenderer } from 'three';
import { GLBType } from 'common/src/glb-iframe/types';
export declare let renderer: WebGLRenderer;
declare const _default: (glbPath: string, glbType: GLBType, baseUri: string, characterMeta?: {
    Type: "Boss";
    BossType: "SirBigEyeLot" | "Goxxer" | "LadyDeVil" | "MasaBot" | "DrPrepper" | "Avocardano" | "HoneyRhingers" | "JiangshiGhost" | "Picasso" | "Warhol" | "Banksy" | "Dali" | "Cthulhu" | "PeterInDaHood" | "PickANick" | "CapnTorrents" | "Peter51" | "VinnieVintage" | "NightShade" | "AguaViva" | "CanCan" | "KelBot" | "WitchBot" | "ConeHead" | "RelicHunter" | "TiredGuy" | "MsTofelees" | "Patch" | "MetaRaider" | "Destructo" | "FakeGhost" | "SorryDave" | "Additive" | "Multiply" | "BluesBrosElwood" | "BluesBrosJake" | "Breadmancer" | "MetaFighter" | "SkullKid" | "Pound" | "Guillotina" | "Blu65" | "SwarmQueen" | "BadBetty" | "BlueShirtGuy" | "Burguy" | "MetaCat" | "GothQueen" | "MetaOctopusGod" | "GreenTracksuit" | "MetaPlayerOne" | "MetaQueen" | "RobotQueenHolo" | "Antoinette" | "HotCakes" | "Crustae-Sean" | "LumberJack" | "UrbanOccultist" | "VenusIII" | "Cleopawtra" | "Illusionist" | "SpaceCowboy" | "NinjaFrogBlack" | "NinjaFrogBlue" | "NinjaFrogOrange" | "NinjaFrogPink" | "Executioner" | "Marvin" | "CapnAquamarine" | "Rumi" | "PlayerOne2384" | "PlayerTwo2384" | "HolographicPlayerOne2384" | "HolographicPlayerTwo2384";
    Accessory: "GameBoy" | "Chilli" | "HotPack" | "FrankieFish" | "AquaBomb" | "Beau" | "Necronomicon" | "Bubbles" | "Hector" | "Flan" | "Hannay" | "Metalite" | "GoldBowl" | "MagicMarble" | "JadeOrb" | "ElderLeaf" | "ClassicSoccerBall" | "Ball" | "MetaverseDaily" | "Jerry" | "IvySprite" | "Trophy" | "Pennant" | "LoveWings" | "BioBomb" | "GameOver" | "BrainBag" | "FrankenWhale" | "BabyRabie" | "Toxie" | "TMND" | "GhostChili" | "MutantSprite" | "BloodBath" | "ZalderLeaf" | "DailyRag" | "LilZ" | "Eyesotope" | "ZORB" | "DeadMouzy" | "WingZ" | "ToxicFlan" | "Zphere" | "PinkScroll" | "HateFork" | "ShortSword" | "SpiralBlaze" | "Tink" | "PureLove" | "Wallet" | "ZenSphere" | "WoodHelm" | "MrFLUF" | "Sporious" | "AlteredSprite" | "PurgeBomb" | "MiniWhale" | "CrawlR" | "GameOn" | "Laika" | "HotFix" | "HiveSupply" | "Daemo" | "NanoSphere" | "Quackinator" | "RedReader" | "CyloBowl" | "AlterLeaf" | "LabRat" | "OR13" | "Opticon" | "HiTechBlob" | "TitanWings" | "Communicator" | "Grappler" | "Healer" | "Illuminator" | "InfoScroll" | "Peeker" | "Quencher" | "TimeKeeper" | "Wayfinder" | "Cooper" | "Flickr" | "Goldie" | "Pocket" | "Slowpoke" | "Squeek" | "BadBatch" | "BoomStick" | "Protector" | "Burger" | "Croissant" | "Donut" | "Drumstick" | "Fries" | "HotDog" | "Juicy" | "Kebab" | "Pizza" | "Sandwich" | "SnoCone" | "Soda" | "Sundae" | "Blob" | "Bomba" | "Casper" | "FunGuy" | "MiniVamp" | "ProtoThingie" | "Slither" | "Sprout" | "Wildfire" | "Beemer" | "Micro" | "Nano" | "Ozmaton" | "Sparky" | "Pixel" | "Chunk" | "Scrappy" | "Livewire" | "Radius" | "Squawk" | "Wyse" | "Blinky" | "Beevis" | "Shuriken" | "Macey" | "FunHammer" | "Bludgeon" | "BigBow" | "FlameSword" | "IceAxe" | "Lasso" | "MagicPlunger" | "O2Tank" | "ProtoFluf" | "CrossBow" | "BlackScroll" | "Can" | "Baton" | "Scamper" | "GoldenIdol" | "FishBurger" | "DevilWings" | "OrangeSoda" | "PowerPack" | "Sqworm" | "ETHCrystal" | "Sceptre" | "Avo" | "BitBag" | "FakePumpkin" | "OrangeScroll" | "Syrup" | "BlueScroll" | "Salem" | "McFly" | "Console9k" | "PicnicStash" | "MasaFork" | "MetaNomicon" | "ButchersCleaver" | "Ssyrena" | "Mochi" | "Hatchet" | "HoneyHive" | "AirSpy" | "MiniUFO" | "Aquabomb" | "ShadeWings" | "WannaCry" | "EatCake" | "Candle" | "Schist" | "PocketWatch" | "FlashGrenade" | "GunPod" | null;
} | {
    Type: "General";
    Family: "Original" | "Zombie" | "ASMilated" | "SuperHeroine";
    Hobby: "Summoner" | "Trainer" | "Gourmet" | "Roboticist" | "Fighter" | "Adventurer" | null;
    Body: "BigEye" | "BlobBeast" | "CrabGuy" | "CryptoNaut" | "GameBear" | "GreenIvy" | "HoneyPot" | "LoveGhost" | "MetaCaptain" | "MissMeow" | "Occultist" | "Octopus" | "OddFrog" | "PlayerOne" | "PlayerTwo" | "Quadrobot" | "Snappy" | "WinterQueen" | "ZenMaster" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "MeloPuff" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss";
    Arms: "BigEye" | "BlobBeast" | "CrabGuy" | "CryptoNaut" | "GameBear" | "GreenIvy" | "HoneyPot" | "LoveGhost" | "MetaCaptain" | "MissMeow" | "Occultist" | "Octopus" | "OddFrog" | "PlayerOne" | "PlayerTwo" | "Quadrobot" | "Snappy" | "WinterQueen" | "ZenMaster" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "MeloPuff" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss";
    Legs: "BigEye" | "BlobBeast" | "CrabGuy" | "CryptoNaut" | "GameBear" | "GreenIvy" | "HoneyPot" | "LoveGhost" | "MetaCaptain" | "MissMeow" | "Occultist" | "Octopus" | "OddFrog" | "PlayerOne" | "PlayerTwo" | "Quadrobot" | "Snappy" | "WinterQueen" | "ZenMaster" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "MeloPuff" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | null;
    Topper: "BigEye" | "BlobBeast" | "CrabGuy" | "CryptoNaut" | "GameBear" | "GreenIvy" | "HoneyPot" | "LoveGhost" | "MetaCaptain" | "MissMeow" | "Occultist" | "Octopus" | "OddFrog" | "PlayerOne" | "PlayerTwo" | "Quadrobot" | "Snappy" | "WinterQueen" | "ZenMaster" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "MeloPuff" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss" | "ArmyCap" | "BackwardsCap" | "BaseballCap" | "BearEars" | "Beret" | "BucketHat" | "RabbitEars" | "CowboyHat" | "Greaser" | "Antlers" | "DroopyEars" | "FlowerHat" | "FlatTop" | "Mane" | "Mohawk" | "PaperboyHat" | "Quiff" | "CatEars" | "TopHat" | "PupEars" | "Braids" | "VintageHat" | "Ponytail" | "Pigtail" | null;
    Eyes: "BigEye" | "BlobBeast" | "CrabGuy" | "CryptoNaut" | "GameBear" | "GreenIvy" | "HoneyPot" | "LoveGhost" | "MetaCaptain" | "MissMeow" | "Occultist" | "Octopus" | "OddFrog" | "PlayerOne" | "PlayerTwo" | "Quadrobot" | "Snappy" | "WinterQueen" | "ZenMaster" | "Valkreja" | "PixelPunch" | "Kelpie" | "Mycellia" | "MeloPuff" | "RosaFuriosa" | "FlamBae" | "AgentEnvy" | "Violaceus" | "SuperMittens" | "Enchantriss";
    Color: "Azure" | "Gold " | "Silver" | "Fabulous" | "Holographic" | "ASMPurple" | "White" | "Pink" | "LightOrange" | "LightGreen" | "DarkOrange" | "DarkGreen" | "Blue" | "Gray" | "Black" | "Purple" | "Gold" | null;
    AccentColor: "Azure" | "Gold " | "Silver" | "Fabulous" | "Holographic" | "ASMPurple" | "White" | "Pink" | "LightOrange" | "LightGreen" | "DarkOrange" | "DarkGreen" | "Blue" | "Gray" | "Black" | "Purple" | "Gold" | null;
    Accessory: "GameBoy" | "Chilli" | "HotPack" | "FrankieFish" | "AquaBomb" | "Beau" | "Necronomicon" | "Bubbles" | "Hector" | "Flan" | "Hannay" | "Metalite" | "GoldBowl" | "MagicMarble" | "JadeOrb" | "ElderLeaf" | "ClassicSoccerBall" | "Ball" | "MetaverseDaily" | "Jerry" | "IvySprite" | "Trophy" | "Pennant" | "LoveWings" | "BioBomb" | "GameOver" | "BrainBag" | "FrankenWhale" | "BabyRabie" | "Toxie" | "TMND" | "GhostChili" | "MutantSprite" | "BloodBath" | "ZalderLeaf" | "DailyRag" | "LilZ" | "Eyesotope" | "ZORB" | "DeadMouzy" | "WingZ" | "ToxicFlan" | "Zphere" | "PinkScroll" | "HateFork" | "ShortSword" | "SpiralBlaze" | "Tink" | "PureLove" | "Wallet" | "ZenSphere" | "WoodHelm" | "MrFLUF" | "Sporious" | "AlteredSprite" | "PurgeBomb" | "MiniWhale" | "CrawlR" | "GameOn" | "Laika" | "HotFix" | "HiveSupply" | "Daemo" | "NanoSphere" | "Quackinator" | "RedReader" | "CyloBowl" | "AlterLeaf" | "LabRat" | "OR13" | "Opticon" | "HiTechBlob" | "TitanWings" | "Communicator" | "Grappler" | "Healer" | "Illuminator" | "InfoScroll" | "Peeker" | "Quencher" | "TimeKeeper" | "Wayfinder" | "Cooper" | "Flickr" | "Goldie" | "Pocket" | "Slowpoke" | "Squeek" | "BadBatch" | "BoomStick" | "Protector" | "Burger" | "Croissant" | "Donut" | "Drumstick" | "Fries" | "HotDog" | "Juicy" | "Kebab" | "Pizza" | "Sandwich" | "SnoCone" | "Soda" | "Sundae" | "Blob" | "Bomba" | "Casper" | "FunGuy" | "MiniVamp" | "ProtoThingie" | "Slither" | "Sprout" | "Wildfire" | "Beemer" | "Micro" | "Nano" | "Ozmaton" | "Sparky" | "Pixel" | "Chunk" | "Scrappy" | "Livewire" | "Radius" | "Squawk" | "Wyse" | "Blinky" | "Beevis" | "Shuriken" | "Macey" | "FunHammer" | "Bludgeon" | "BigBow" | "FlameSword" | "IceAxe" | "Lasso" | "MagicPlunger" | "O2Tank" | "ProtoFluf" | "CrossBow" | "BlackScroll" | "Can" | "Baton" | "Scamper" | "GoldenIdol" | "FishBurger" | "DevilWings" | "OrangeSoda" | "PowerPack" | "Sqworm" | "ETHCrystal" | "Sceptre" | "Avo" | "BitBag" | "FakePumpkin" | "OrangeScroll" | "Syrup" | "BlueScroll" | "Salem" | "McFly" | "Console9k" | "PicnicStash" | "MasaFork" | "MetaNomicon" | "ButchersCleaver" | "Ssyrena" | "Mochi" | "Hatchet" | "HoneyHive" | "AirSpy" | "MiniUFO" | "Aquabomb" | "ShadeWings" | "WannaCry" | "EatCake" | "Candle" | "Schist" | "PocketWatch" | "FlashGrenade" | "GunPod" | null;
} | undefined) => Promise<void>;
export default _default;
